validation.py: Annotate function args and return values (#317)
* :label: annotate function args and return values

Starting with the validation module:

- I think (X, y) might need some custom Union type to handle both numpy arrays and pandas dataframe, etc.
- All of the "assert" functions return None.

Ref #307

* refactor: :label: swap npt.NDArray -> np.ndarray

np.ndarray seems more consistent with the rest of the repo.
Maybe it's necessary to go back to npt.NDArray when disallowing generics?

See numpy docs: https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray

* refactor: :fire: remove unused import

* :label: unconstrain X input types

* :bug: handle label type issues

- Have to restrict the output of labels_to_array to pass mypy checks.
- Returning the values of pd.Series isn't type-stable.

* :label: include np.generic in arg-type union

* test: :white_check_mark: test labels_to_array

* :label: add type aliases for X and y

* :rotating_light: ignore type-checks for pandas indexing assertions

CI typechecker runs on Python 3.10 which gives this error:

'cleanlab/internal/validation.py:125: error: No overload variant of "__getitem__" of "_iLocIndexerSeries" matches argument type "List[int]"'

It should be fine to let mypy ignore these expressions as they don't return anything.

* :goal_net: specify errors to ignore

"type: ignore" doesn't pass strict mypy type-checks unless the specific errors are provided

* :label: annotate label series to array